# Generated by Django 2.0.2 on 2022-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0002_auto_20220508_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('plate', models.CharField(max_length=60)),
            ],
        ),
    ]
