# Generated by Django 2.0.2 on 2022-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0004_dayfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayfood1',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('plate', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
            ],
        ),
    ]
