# Generated by Django 2.0.2 on 2022-05-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0005_dayfood1'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=60)),
                ('expire', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='dayfood',
        ),
    ]
