# Generated by Django 2.0.2 on 2022-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0006_auto_20220510_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=60)),
                ('quan', models.CharField(max_length=60)),
            ],
        ),
    ]
