# Generated by Django 2.0.2 on 2022-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0007_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill1',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=60)),
                ('quan', models.CharField(max_length=60)),
                ('ids', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='bill',
        ),
    ]
