# Generated by Django 2.0.2 on 2022-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0009_auto_20220511_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill3',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
