# Generated by Django 2.0.2 on 2022-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0012_auto_20220517_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats1',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=60)),
            ],
        ),
    ]
