# Generated by Django 3.2.14 on 2022-07-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0013_stats1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ulogin1',
            old_name='collage_id',
            new_name='college_id',
        ),
    ]
